wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1724302799
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 61
      4: 3.10.12
      5: 0.17.7
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 64
